name: Docker Build and Push

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
   runs-on: ubuntu-latest
   steps:
     -
       name: Checkout
       uses: actions/checkout@v2
     -
       name: "See last commit message"
       id: test_here
       run: echo ::set-output name=test_commit_message::$(git log --format=%%B -n 1 HEAD^2)
     -
       name: Set up QEMU
       uses: docker/setup-qemu-action@v1
     -
       name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v1
     -
       name: Login to DockerHub
       uses: docker/login-action@v1
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB }}
     -
       name: Build and push
       id: docker_build
       uses: docker/build-push-action@v2
       with:
         context: .
         file: ./Dockerfile
         platforms: linux/amd64
         push: true
         tags: dmukaliy/python-helloworld:latest

