name: Docker Build and Push

on:
  push:
    branches:
      - 'master'

jobs:
  test:
   runs-on: ubuntu-latest
   steps:
     -
       name: Checkout
       uses: actions/checkout@v2
     -
       name: "See last commit message"
       id: test_here
       run: echo ::set-output name=pr_commit_message::$(git log --format=%%B -n 1 HEAD)
     -
       name: "again"
       id: random-color-generator
       run: echo "::set-output name=action_fruit::strawberry"
     - name: Get color
       run: echo "The selected color is ${{ steps.test_here.outputs.pr_commit_message }}"
   outputs:
    pr_commit_message: $( [ -z "${{ steps.test_here.outputs.pr_commit_message }}" ] && echo "${{ steps.test_here.outputs.pr_commit_message }}" )
  test2:
   runs-on: ubuntu-latest
   needs: test
   steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    - 
      name: echo here
      run: echo "The check" 
    -
      name: "See last commit message"
      run: echo ${{ needs.test.outputs.pr_commit_message }}
  docker:
   runs-on: ubuntu-latest
   steps:
     -
       name: Checkout
       uses: actions/checkout@v2
     -
       name: Set up QEMU
       uses: docker/setup-qemu-action@v1
     -
       name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v1
     -
       name: Login to DockerHub
       uses: docker/login-action@v1
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB }}
     -
       name: Build and push
       id: docker_build
       uses: docker/build-push-action@v2
       with:
         context: .
         file: ./Dockerfile
         platforms: linux/amd64
         push: true
         tags: dmukaliy/python-helloworld:latest
  
